env:
  node: true
  es2020: true
  browser: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: 12
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  linebreak-style: 0
  no-param-reassign: ["error", { "props": false }]

plugins:
  - jest
